name: Set BUILD_NUMBER

on: [workflow_call]

env:
  CURL_OPTIONS: "--fail-with-body --location --show-error --silent"
  DEFAULT_BUILD_NUMBER: "1"
  BUILD_NUMBER_PREFIX: "build"

defaults:
  run:
    shell: bash

jobs:
  define-build-number:
    runs-on: ubuntu-latest
    steps:
      - name: get BUILD_NUMBER
        run: |
          echo "BUILD_NUMBER=$(curl ${{ env.CURL_OPTIONS }} \
          -X GET \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          ${{ github.api_url }}/repos/${{ github.repository }}/git/matching-refs/tags/${{ env.BUILD_NUMBER_PREFIX}}/ \
          | jq -r '.[].ref' \
          | cut --delimiter="/" --only-delimited --fields 4 \
          | sort --general-numeric-sort \
          | tail -1 )" >> "$GITHUB_ENV"

      - name: increment BUILD_NUMBER
        run: |
          INTEGER_REGEX='^[1-9][0-9]*$'
          if [[ ${{ env.BUILD_NUMBER }} =~ $INTEGER_REGEX ]]; then
            echo "::notice title=BUILD_NUMBER::✅ BUILD_NUMBER is int"
            echo "BUILD_NUMBER=$((${{ env.BUILD_NUMBER }} + 1))" >> $GITHUB_ENV
          else
            echo "::notice title=BUILD_NUMBER::❌ BUILD_NUMBER not an int"
            echo "BUILD_NUMBER=${{ env.DEFAULT_BUILD_NUMBER }}" >> $GITHUB_ENV
          fi
